import MarkdownLayout, { Header } from '@/components/MarkdownLayout'
import type { Metadata } from 'next'

import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Header />
        <div
          className="prose 
            prose-headings:mt-4 
            prose-headings:font-semibold 
            prose-headings:text-black 
            prose-h1:text-3xl 
            prose-h2:text-2xl 
            prose-h3:text-xl 
            prose-h4:text-lg 
            prose-h5:text-base 
            prose-h6:text-sm 
            dark:prose-headings:text-white 
            prose-a:no-underline
            max-w-none
            prose-base
            "
        >
          <MarkdownLayout>{children}</MarkdownLayout>
        </div>
      </body>
    </html>
  )
}
