import { ThemeProvider } from '@/context/ThemeProvider'
import { setInitialTheme } from '@/lib/setInitialTheme'
import { Analytics } from '@vercel/analytics/react'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: setInitialTheme }} />
      </head>
      <body className="antialiased">
        <ThemeProvider>
          {/* <Header /> */}
          {children}
          <Analytics />
        </ThemeProvider>
      </body>
    </html>
  )
}
